{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.vmbbi",
    "module": "lib",
    "version": "1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.vmbbi",
          "module": "multidim",
          "version": {
            "requires": "2.1.6-1.21.1"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "scheduler",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "queue",
          "version": {
            "requires": "1.1.0-1.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1.jar",
          "url": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1.jar",
          "size": 682457,
          "sha512": "afdf7a582e763672c52bf74f443f1a0bf467669b2c0ac2caaa5fbb4234e588a824da46971d68b8048a8d96e7c539ef09ff6722b43f974a3eb8cf75d931dbb895",
          "sha256": "ceaa5211015d85c86b61b6771213f1023496543dcc7e660aaa544eeccd116f97",
          "sha1": "84da603cdae591a5b1825b704894d44d61beb5bf",
          "md5": "27bd2bd76d5d12138a89065ff953461e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.vmbbi",
          "module": "multidim",
          "version": {
            "requires": "2.1.6-1.21.1"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "scheduler",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "queue",
          "version": {
            "requires": "1.1.0-1.20"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.15+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1.jar",
          "url": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1.jar",
          "size": 682457,
          "sha512": "afdf7a582e763672c52bf74f443f1a0bf467669b2c0ac2caaa5fbb4234e588a824da46971d68b8048a8d96e7c539ef09ff6722b43f974a3eb8cf75d931dbb895",
          "sha256": "ceaa5211015d85c86b61b6771213f1023496543dcc7e660aaa544eeccd116f97",
          "sha1": "84da603cdae591a5b1825b704894d44d61beb5bf",
          "md5": "27bd2bd76d5d12138a89065ff953461e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1-sources.jar",
          "url": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1-sources.jar",
          "size": 351924,
          "sha512": "c552348d38c49be2453eb16c9b5af91fd3f69ed5f3a5b4ee1b8352041f75ec5b962c8ef342a62acdb6aa2868add440ea5f0bb1079edaf9d1ce1c3ae06ee5870f",
          "sha256": "e5f4d44ab8ed8994b260c584b180a95a5dab2eae02cabe20c0f00cd56523fb42",
          "sha1": "19b30e2c0f7aad22b881a463acd7a1f4815fbe09",
          "md5": "b04b56a3c7ee21826379c544fc1bc2bc"
        }
      ]
    }
  ]
}
