{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.vmbbi",
    "module": "multidim",
    "version": "2.1.4-1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1.jar",
          "url": "multidim-2.1.4-1.21.1.jar",
          "size": 49669,
          "sha512": "a307d6fadffdefdeaa16f5009bc086af7fed17586cb8be9d4b3b80f48d9febe4626d5b220244dd10d5334ac65dee18dfff5eecf5ce43e86c60fa3ec3c93676c0",
          "sha256": "e741bc1ac6713dde0d8d130caa8f8575be18b003a1dbbe4a0f64b75f04762a87",
          "sha1": "c8c9c70c653e7b56139e6a90193f4b632c7874ce",
          "md5": "c56a47deebc68f757de27ec206a47109"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.15+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1.jar",
          "url": "multidim-2.1.4-1.21.1.jar",
          "size": 49669,
          "sha512": "a307d6fadffdefdeaa16f5009bc086af7fed17586cb8be9d4b3b80f48d9febe4626d5b220244dd10d5334ac65dee18dfff5eecf5ce43e86c60fa3ec3c93676c0",
          "sha256": "e741bc1ac6713dde0d8d130caa8f8575be18b003a1dbbe4a0f64b75f04762a87",
          "sha1": "c8c9c70c653e7b56139e6a90193f4b632c7874ce",
          "md5": "c56a47deebc68f757de27ec206a47109"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1-sources.jar",
          "url": "multidim-2.1.4-1.21.1-sources.jar",
          "size": 17065,
          "sha512": "34f6ccefa624dded922dfe059761f492e39f27ab6fa4aa56f80e5a4fa989d4593ea1391ce0cb482f6c2f4b3f41e893e461ffff574126f60c96ab492ce0b2a4b8",
          "sha256": "0e1b99450adef3fa282a9c184acbad4255c0b2fb4108aeb1da8e6284aaecf069",
          "sha1": "5f08159324201b2d75036b060e6d64f2f198276b",
          "md5": "fc0a5145ef7e850ba29d20eab8d39f40"
        }
      ]
    }
  ]
}
