{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.vmbbi",
    "module": "multidim",
    "version": "2.1.4-1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1.jar",
          "url": "multidim-2.1.4-1.21.1.jar",
          "size": 49721,
          "sha512": "e26aaac9c2bac1a598e91589885306d7953350332c485be9df827193b7a735f0469a4dc5d38f50e693aca4abaa146fdb820c65d98fed02159755c6c7a721e622",
          "sha256": "07827eb98783f2b922d0763d93946988aa3c148a10eafcdeec35c50ac41f66fb",
          "sha1": "16276d7f26c4edc8d3961bf78a78eb7b57d005b2",
          "md5": "7a89fdb7c109a942a3d7b55851c0243a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.15+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1.jar",
          "url": "multidim-2.1.4-1.21.1.jar",
          "size": 49721,
          "sha512": "e26aaac9c2bac1a598e91589885306d7953350332c485be9df827193b7a735f0469a4dc5d38f50e693aca4abaa146fdb820c65d98fed02159755c6c7a721e622",
          "sha256": "07827eb98783f2b922d0763d93946988aa3c148a10eafcdeec35c50ac41f66fb",
          "sha1": "16276d7f26c4edc8d3961bf78a78eb7b57d005b2",
          "md5": "7a89fdb7c109a942a3d7b55851c0243a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1-sources.jar",
          "url": "multidim-2.1.4-1.21.1-sources.jar",
          "size": 17020,
          "sha512": "4e116f577e7c6fdddd91d4fbba2a82523a42f7e04be0a05b4a0c220164eecb763977edc774ca5e233f81aa15b4af39170d139838cd5a2039f3e5d86ef81ea98e",
          "sha256": "448ef7477ab75ba7e14901ef5a1abdea381acfdb9f8e85d426263bac0994b242",
          "sha1": "7fc48db956737af9c6d19ce2dcff71874bc5b2ff",
          "md5": "53c41e1ffce2207a3e26e1293bbd2926"
        }
      ]
    }
  ]
}
