{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.vmbbi",
    "module": "multidim",
    "version": "2.1.4-1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1.jar",
          "url": "multidim-2.1.4-1.21.1.jar",
          "size": 49669,
          "sha512": "a307d6fadffdefdeaa16f5009bc086af7fed17586cb8be9d4b3b80f48d9febe4626d5b220244dd10d5334ac65dee18dfff5eecf5ce43e86c60fa3ec3c93676c0",
          "sha256": "e741bc1ac6713dde0d8d130caa8f8575be18b003a1dbbe4a0f64b75f04762a87",
          "sha1": "c8c9c70c653e7b56139e6a90193f4b632c7874ce",
          "md5": "c56a47deebc68f757de27ec206a47109"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.15+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1.jar",
          "url": "multidim-2.1.4-1.21.1.jar",
          "size": 49669,
          "sha512": "a307d6fadffdefdeaa16f5009bc086af7fed17586cb8be9d4b3b80f48d9febe4626d5b220244dd10d5334ac65dee18dfff5eecf5ce43e86c60fa3ec3c93676c0",
          "sha256": "e741bc1ac6713dde0d8d130caa8f8575be18b003a1dbbe4a0f64b75f04762a87",
          "sha1": "c8c9c70c653e7b56139e6a90193f4b632c7874ce",
          "md5": "c56a47deebc68f757de27ec206a47109"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1-sources.jar",
          "url": "multidim-2.1.4-1.21.1-sources.jar",
          "size": 17065,
          "sha512": "b1843d3901aa18a0867d99a22c9dfd3d0f32a1747ba1ebe519db91746b6856f55f02e8081f5849dabdd9b94aaec0ca25556734fa95e38e9f87c058d0420a9b4d",
          "sha256": "02fd20b34279634098b6a9aa2100cf1bfb0927f7e21307ea48def5b74370962c",
          "sha1": "be8ce3573c28474a97c6d048c5877320011352f9",
          "md5": "ecea71009e0d7dab5cb577fcd9026f93"
        }
      ]
    }
  ]
}
