{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.vmbbi",
    "module": "lib",
    "version": "1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.vmbbi",
          "module": "multidim",
          "version": {
            "requires": "2.1.6-1.21.1"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "scheduler",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "queue",
          "version": {
            "requires": "1.1.0-1.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1.jar",
          "url": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1.jar",
          "size": 682809,
          "sha512": "45701fcdc6e27b78bee469d5187ae4c05cced6f555d8323be5d7bd0fdc053f01b3be92ee938df206f5a1cd01757b0ba9987fc20e1cc718c50e1a58c98004db44",
          "sha256": "8c613bf6b29b438d53a9269ba3768f6f33bef949a90ca92beb3a96de14bc80ff",
          "sha1": "7fede8162aa1a2493d70615ee539d622f134c8f9",
          "md5": "105bda7320ec9719cd0763d0dcbbce8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.vmbbi",
          "module": "multidim",
          "version": {
            "requires": "2.1.6-1.21.1"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "scheduler",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "queue",
          "version": {
            "requires": "1.1.0-1.20"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.15+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1.jar",
          "url": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1.jar",
          "size": 682809,
          "sha512": "45701fcdc6e27b78bee469d5187ae4c05cced6f555d8323be5d7bd0fdc053f01b3be92ee938df206f5a1cd01757b0ba9987fc20e1cc718c50e1a58c98004db44",
          "sha256": "8c613bf6b29b438d53a9269ba3768f6f33bef949a90ca92beb3a96de14bc80ff",
          "sha1": "7fede8162aa1a2493d70615ee539d622f134c8f9",
          "md5": "105bda7320ec9719cd0763d0dcbbce8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1-sources.jar",
          "url": "lib-1.1.16+1.21.1-fix-1.21.1-trust-bro-trust-dev+mc.1.21.1-sources.jar",
          "size": 352104,
          "sha512": "4f3879bea7ec2d65b79ff1576ada0e9653c2dd18aa93f4798595945abc11986b7aaea68c4853471113b488be61781565e27609fbb1b3eb19936f8d70cf38dcd2",
          "sha256": "06f103cad2bff08b2faa88737bf8df7fca054383340e786f8972861292a15f0a",
          "sha1": "bf046b5b07a8a47cb4db28ebaeb6d7994dd4333f",
          "md5": "c79b6db64b6706d9ce0b55ff874f37ed"
        }
      ]
    }
  ]
}
