{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.vmbbi",
    "module": "multidim",
    "version": "2.1.4-1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1.jar",
          "url": "multidim-2.1.4-1.21.1.jar",
          "size": 49665,
          "sha512": "92b3d888e5dc9b709905434a47313f23d632f132c7825254bb1afc0514d6f0d44af80b0a03c2895a5a57bce0b02072a797c9d1b7b684ecb4ce327ee24b1eb550",
          "sha256": "27a8a325f791b3153041807776e88a607f9b9bb38719a62c56aa4ef98e4292e4",
          "sha1": "a18c6b9d3529438c6356b4dc58f3f3898fd551aa",
          "md5": "213136606874a7ddb3db1eb7f9a8437d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.15+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1.jar",
          "url": "multidim-2.1.4-1.21.1.jar",
          "size": 49665,
          "sha512": "92b3d888e5dc9b709905434a47313f23d632f132c7825254bb1afc0514d6f0d44af80b0a03c2895a5a57bce0b02072a797c9d1b7b684ecb4ce327ee24b1eb550",
          "sha256": "27a8a325f791b3153041807776e88a607f9b9bb38719a62c56aa4ef98e4292e4",
          "sha1": "a18c6b9d3529438c6356b4dc58f3f3898fd551aa",
          "md5": "213136606874a7ddb3db1eb7f9a8437d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multidim-2.1.4-1.21.1-sources.jar",
          "url": "multidim-2.1.4-1.21.1-sources.jar",
          "size": 17028,
          "sha512": "c0a2a72d1d083816a5e101e7df562b6dc2edd4f6bf24b079b3e4c6d3922bf7f6f8f5cf97e69bd66a2dc14a20415407954e86ab69a4ac2f02b9c0865223678b00",
          "sha256": "a80d6886ae056a22c5d4dcedb7cc18a5ac30e5f603fe6818d6d828eb10600cad",
          "sha1": "16ec76976410dd20f61df872ee5c61a239d0d301",
          "md5": "2660c594f449978a4d110ae74cd02cfb"
        }
      ]
    }
  ]
}
